export const mockStudentLists = [
  {
    id: 1,
    name: 'Juan Dela Cruz',
    email: 'juan.delacruz@student.cvsu.edu.ph',
    course: 'Bachelor of Science in Information Technology',
    section: 'BSIT3-1',
    academicYear: '2024-2025',
    semester: '1st' as const,
    status: 'active' as const,
    hte: 'Tech Solutions Inc.',
    startDate: '2024-01-15',
    endDate: '2024-05-15',
  },
  {
    id: 2,
    name: 'Maria Santos',
    email: 'maria.santos@student.cvsu.edu.ph',
    course: 'Bachelor of Science in Computer Science',
    section: 'BSCS3-2',
    academicYear: '2024-2025',
    semester: '1st' as const,
    status: 'active' as const,
    hte: 'Digital Systems Corp.',
    startDate: '2024-01-15',
    endDate: '2024-05-15',
  },
  {
    id: 3,
    name: 'Pedro Lopez',
    email: 'pedro.lopez@student.cvsu.edu.ph',
    course: 'Bachelor of Science in Information Technology',
    section: 'BSIT3-4',
    academicYear: '2024-2025',
    semester: 'summer' as const,
    status: 'completed' as const,
    hte: 'Web Dev Studios',
    startDate: '2023-09-01',
    endDate: '2023-12-15',
  },
  {
    id: 4,
    name: 'Ana Rodriguez',
    email: 'ana.rodriguez@student.cvsu.edu.ph',
    course: 'Bachelor of Science in Computer Science',
    section: 'BSCS3-5',
    academicYear: '2024-2025',
    semester: '2nd' as const,
    status: 'inactive' as const,
  },
];